sentencepiece:
  tokenizer:
    models:
      name: wikija_sentencepiece.model
      url: https://s3-ap-northeast-1.amazonaws.com/models.inoue-kobo.com/text-vectorian/sentencepiece/wikija_sentencepiece.model
  vectorizer:
    models:
      name: wikija_sentencepieced_word2vec.model
      url: https://s3-ap-northeast-1.amazonaws.com/models.inoue-kobo.com/text-vectorian/sentencepiece/wikija_sentencepieced_word2vec.model